### ISSUE TITLE
React Native Login & Registration Pages with API connection

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-app#3]
<img width="1157" alt="image" src="https://github.com/eronka/culero-app/assets/4149765/a650b943-33ae-4cbd-a4e8-e69b823260c4">

As a starting point, we will need to have initial registration / login flow built.

Please find this API documentation
https://api2.culero.com/docs

Below is the link to Figma for more details on the UI.
https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Culero?type=design&mode=design&t=TWhciMegkB4oe5FT-0

**Comment by syedbarimanjan** [comment]
A short note about the figma designs that you should create a seperate page for every issue and put the designs which are to be build on that page and provide the link here.

**Comment by hsb1007** [comment]
> A short note about the figma designs that you should create a seperate page for every issue and put the designs which are to be build on that page and provide the link here.

Yes that would be the goal to make it easier but for now it needs to be the way it is unfortunately! 

Thank you for your suggestion though!

**Comment by neo773** [comment]
/attempt #3


<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;3 eronka bounties <br/> + 110 bounties from 22 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvdpfyz20006i90cena6ff6b/cancel-attempt) |

**Comment by neo773** [comment]
Attempting as we discussed this prior to issue

**Comment by syedbarimanjan** [comment]
> Attempting as we discussed this prior to issue

Should I take the other one then?

**Comment by hsb1007** [comment]
> > Attempting as we discussed this prior to issue
> 
> Should I take the other one then?

Yes please! I left a message in our discord!

**Comment by syedbarimanjan** [comment]
Is the other one open then should I work on it or is it also decided

**Comment by hsb1007** [comment]
I am closing this and will re open when components are built in issue 5

**Comment by adelinaenache** [comment]
/attempt #3

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/adelinaenache) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @adelinaenache | &nbsp;&nbsp;&nbsp;1 eronka bounty <br/> + 3 bounties from 1 project | <div align="center">JavaScript, TypeScript, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvdpfyz20006i90cena6ff6b/cancel-attempt) |
