### ISSUE TITLE
React Native building user dashboard components 

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-app#4]
React Native building user dashboard components such as navigation / some of the card component in the dashboard (highlighted pages below

<img width="949" alt="image" src="https://github.com/eronka/culero-app/assets/4149765/b6a24c82-3561-4b1d-ba8f-f6c837158c27">

And please have basic API connected to the UI where applicable following the structure set in https://github.com/eronka/culero-app/issues/3 

API Doc

https://api2.culero.com/docs

Below is the link to Figma for more details on the UI.
https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Culero?type=design&mode=design&t=TWhciMegkB4oe5FT-0

**Comment by syedbarimanjan** [comment]
/attempt #4

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvdplltg0004l80ce6pcrvex/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by hsb1007** [comment]
Assigned!

**Comment by hsb1007** [comment]
Closing for now and will reopen when component is ready
