### ISSUE TITLE
Component to be built

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-app#5]
<img width="950" alt="image" src="https://github.com/eronka/culero-app/assets/4149765/27676bed-9b74-4a76-83af-366f7490a4a5">

**Comment by hsb1007** [comment]
This is to be built by syedbarimanjan

**Comment by syedbarimanjan** [comment]
/attempt #5

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvdq339a0004kz0cdtjtouye/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by hsb1007** [comment]
How are you doing ! anything I can do to support!

**Comment by syedbarimanjan** [comment]
> How are you doing ! anything I can do to support!

Thanks I am working on it the first day I wasnt feeling well but the second day I made reasonable progress will open a pr. I mainly focused on building the components which will be used in the login and registration flow so neo can start work on it and it is not delayed.

**Comment by syedbarimanjan** [comment]
@neo773 could you check discord.

**Comment by hsb1007** [comment]
Replaced by issue #6
