### ISSUE TITLE
UI response to be instant without having to wait for API response or have loading icon

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-app#54]
There are user actions where UI hangs while it is waiting for API response. 

it makes the app seem unresponsive.

Some of the examples are

- Login / Signup
- Leaving Reviews
- Deleting Reviews

They need to have instant reaction.

The search feature need to have 'loading' gif as UI reaction so user knows what's happening

**Comment by hsb1007** [comment]
@adelinaenache  Anything I can assist on this?

Thanks!

**Comment by adelinaenache** [comment]
> @adelinaenache Anything I can assist on this?
> 
> Thanks!

I'm on it
