### ISSUE TITLE
React Native components to build

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-app#6]
<img width="811" alt="image" src="https://github.com/eronka/culero-app/assets/4149765/4e16048d-961a-480f-8572-2e5f9c47064d">

We have RN Boilerplate put together and we need someone to build a set of UIs built in React Native so we can start developing the rest of the UI efficiently.

For more details about the UI / component, please request for access to Figma below

https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4?node-id=0:1&locale=en&type=design

**Comment by adelinaenache** [comment]
/attempt #6

<div id="algora" />

| [Algora profile](https://console.algora.io/@/adelinaenache) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @adelinaenache | 3 bounties from 1 project | <div align="center">JavaScript, TypeScript, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvkx8ylg0006l90dc93xgdzf/cancel-attempt) |

**Comment by hsb1007** [comment]
> /attempt #6
> 
> [Algora profile](https://console.algora.io/@/adelinaenache)	Completed bounties	Tech	Active attempts	Options
> @adelinaenache	3 bounties from 1 project	
> JavaScript, TypeScript,
> Python & more
> [Cancel attempt](https://console.algora.io/api/bounties/clvkx8ylg0006l90dc93xgdzf/cancel-attempt)

Your access request has been granted!
