### ISSUE TITLE
Write a review  page

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-app#9]
<img width="1037" alt="image" src="https://github.com/eronka/culero-app/assets/4149765/1ab262c2-7cd8-495d-afb3-3659d9a7cff5">
Now that we have componetns built, please have write a review page

**Comment by adelinaenache** [comment]
/attempt #9

<div id="algora" />

| [Algora profile](https://console.algora.io/@/adelinaenache) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @adelinaenache | &nbsp;&nbsp;&nbsp;1 eronka bounty <br/> + 3 bounties from 1 project | <div align="center">JavaScript, TypeScript, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvqd50id0004jp09r2xdexmu/cancel-attempt) |

**Comment by hrshkshri** [comment]
Hey @hsb1007 
IG this issue is solved, right?
